# Aplicacion
spring.application.name=progreso2

# RabbitMQ
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=admin
spring.rabbitmq.password=admin123

# Camel
camel.springboot.main-run-controller=true

# Directorios de salida
app.outbox.path=data/outbox/auditoria-citas.csv
app.errors.path=data/errors/citas-rechazadas.log